[package]
name = "{{ project_name }}_persistence"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-rustls", "uuid", "migrate", "macros"] }
tokio = { version = "1", features = ["rt"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
url = { version = "2", features = ["serde"] }
